Repository Solving-Our-Meals/ukki-front, pull requests merged in 2024-12, with the labels that each got.

#8 [FEATURE][addHeader] 반응형 헤더
  package-lock.json
  src/App.js
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/common/header/css/reset.css
  src/common/header/css/reset.css.map
  src/common/header/css/reset.scss
  src/common/header/images/PROFILE.zip
  src/common/header/images/PROFILE/1.png
  src/common/header/images/PROFILE/10.png
  src/common/header/images/PROFILE/2.png
  src/common/header/images/PROFILE/3.png
  src/common/header/images/PROFILE/4.png
  src/common/header/images/PROFILE/5.png
  src/common/header/images/PROFILE/6.png
  src/common/header/images/PROFILE/7.png
  src/common/header/images/PROFILE/8.png
  src/common/header/images/PROFILE/9.png
  src/common/header/images/header-logo.png
  src/common/header/images/menu-icon.png
  src/common/header/images/profile.png
  src/common/header/layouts/Layouts.js
Labels: feature

#12 [FIX][fixHeader]헤더 수정
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/common/header/css/reset.scss
  src/common/header/layouts/Layouts.js
  src/reset.css
  src/reset.css.map
  src/reset.scss
  src/user/pages/info/Info.js
  src/user/pages/info/css/Info.css
  src/user/pages/info/css/Info.css.map
  src/user/pages/info/css/Info.scss
  src/user/pages/info/image/character-main.png
  src/user/pages/info/image/img-logo.png
  src/user/pages/info/image/styleguide.jpg
  src/user/pages/info/image/styleguide.svg
  src/user/pages/info/image/talk-1.png
  src/user/pages/info/image/talk-2.png
  src/user/pages/info/image/talk-bg.png
  src/user/pages/info/image/text-logo.png
  src/user/pages/info/image/ukki logo.jpg
  src/user/pages/info/image/ukki logo.svg
Labels: duplicate

#13 [FEATURE][addFooter]반응형 푸터
  src/App.js
  src/admin/layouts/.js
  src/admin/layouts/AdminLayout.js
  src/common/footer/components/Footer.js
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/common/footer/css/reset.module.css
  src/common/footer/css/reset.module.css.map
  src/common/footer/css/reset.module.scss
  src/common/footer/images/footer-logo.png
  src/common/header/layouts/Layouts.js
  src/store/layouts/.js
  src/store/layouts/StoreLayout.js
  src/user/layouts/.js
  src/user/layouts/UserLayout.js
Labels: feature

#17 [FEATURE][Inquiry]문의하기
  src/App.js
  src/common/inquiry/api/.js
  src/common/inquiry/api/inquiryCategoryAPI.js
  src/common/inquiry/components/doinquiry.js
  src/common/inquiry/css/doinquiry.css
  src/common/inquiry/css/doinquiry.css.map
  src/common/inquiry/css/doinquiry.scss
  src/common/inquiry/css/reset.css
  src/common/inquiry/css/reset.css.map
  src/common/inquiry/css/reset.scss
  src/common/inquiry/layouts/.js
  src/common/inquiry/pages/.js
Labels: feature

#27 [FEATURE][informationPage] 소개 페이지 완성
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/user/pages/info/Info.js
  src/user/pages/info/css/Info.css
  src/user/pages/info/css/Info.css.map
  src/user/pages/info/css/Info.scss
Labels: feature

#28 [FEATURE][InquiryModal]문의하기 모달 제작
  src/common/inquiry/css/doinquiry.css
  src/common/inquiry/css/doinquiry.css.map
  src/common/inquiry/css/doinquiry.scss
  src/user/css/reset.css
Labels: fix

#30 [FEATURE][StoreDetail]가게 상세페이지 구현
  src/App.js
  src/admin/inquiry/api/.js
  src/admin/inquiry/components/.js
  src/admin/inquiry/css/.js
  src/admin/inquiry/pages/.js
  src/admin/layouts/AdminLayout.js
  src/common/floatingBar/components/FloatingBar.js
  src/common/floatingBar/css/floatingbar.module.css
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/floatingBar/css/floatingbar.module.scss
  src/common/floatingBar/images/floatingBar-logo.png
  src/common/floatingBar/images/floating_home.png
  src/common/floatingBar/images/floating_inquiry.png
  src/common/floatingBar/images/floating_top.png
  src/common/footer/components/Footer.js
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/common/footer/css/reset.module.css
  src/common/footer/css/reset.module.css.map
  src/common/footer/css/reset.module.scss
  src/common/footer/images/footer-logo.png
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/header/layouts/Layouts.js
  src/common/inquiry/css/reset.css
  src/common/inquiry/css/reset.css.map
  src/common/inquiry/layouts/.js
  src/common/reset/reset.css
  src/common/reset/reset.css.map
  src/common/reset/reset.scss
  src/reset.css.map
  src/store/layouts/BossLayout.js
  src/store/pages/bossStore/api/.js
  src/store/pages/bossStore/components/.js
  src/store/pages/bossStore/css/.js
  src/store/pages/bossStore/pages/.js
  src/user/css/reset.css.map
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.css.map
  src/user/layouts/css/userlayout.module.scss
  src/user/pages/signup/api/.js
  src/user/pages/signup/components/.js
  src/user/pages/signup/css/Signup.css
  src/user/pages/signup/css/reset.css
  src/user/pages/signup/css/reset.css.map
  src/user/pages/signup/css/reset.scss
  src/user/pages/signup/pages/Signup.js
  src/user/pages/storedetail/api/.js
  src/user/pages/storedetail/components/.js
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#33 [FEATURE][SignupId]회원가입 아이디 부분 완료
  package.json
  src/App.js
  src/user/pages/signup/css/Signup.css
  src/user/pages/signup/pages/Signup.js
Labels: feature

#34 [FEATURE][StoreDetail]가게 상세조회 가게 정보 조회
  src/user/pages/storedetail/api/.js
  src/user/pages/storedetail/api/KeywordAPI.js
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/images/inverted_triangle.png
  src/user/pages/storedetail/images/mapPointer-logo.png
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#35 [FEATURE][DoInquiry]문의하기 90%완료
  src/App.js
  src/common/inquiry/api/inquiryCategoryAPI.js
  src/common/inquiry/components/UserDoInquiry.js
  src/common/inquiry/components/doinquiry.js
  src/common/inquiry/css/doinquiry.css
Labels: feature

#37 [FEATURE][Footer] 스타일 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/common/footer/css/reset.module.css
  src/common/footer/css/reset.module.css.map
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/reset.css
  src/common/header/css/reset.css.map
  src/common/inquiry/css/reset.css
  src/common/inquiry/css/reset.css.map
  src/common/reset/reset.css
  src/common/reset/reset.css.map
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.css.map
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/signup/css/reset.css
  src/user/pages/signup/css/reset.css.map
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature

#38 [FEATURE][Signup]회원가입 페이지 구현(미완성)
  package-lock.json
  src/user/pages/signup/css/Signup.css
  src/user/pages/signup/pages/Signup.js
Labels: feature

#40 [FEATURE][StoreDetail]가게 페이지 상세 조회 구현 중
  src/common/floatingBar/css/floatingbar.module.css
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/footer/components/Footer.js
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/common/footer/css/reset.module.css
  src/common/footer/css/reset.module.css.map
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/reset.css
  src/common/header/css/reset.css.map
  src/common/inquiry/css/reset.css
  src/common/inquiry/css/reset.css.map
  src/common/reset/reset.css
  src/common/reset/reset.css.map
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.css.map
  src/user/layouts/css/userlayout.module.scss
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/signup/css/reset.css
  src/user/pages/signup/css/reset.css.map
  src/user/pages/storedetail/api/KeywordAPI.js
  src/user/pages/storedetail/components/.js
  src/user/pages/storedetail/components/Banner.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/banner.module.css.map
  src/user/pages/storedetail/css/banner.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#46 [FEATURE][mainFront] 메인페이지 레이아웃
  src/user/pages/main/Main.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature

#47 [FEATURE][inquiry] 가게문의이동 모달
  src/App.js
  src/common/inquiry/components/StoreDoInquiry.js
  src/common/inquiry/components/StoreInquiryEnter.js
  src/common/inquiry/components/StoreInquiryList.js
  src/common/inquiry/components/UserDoInquiry.js
  src/common/inquiry/css/StoreInquiryList.css
  src/common/inquiry/css/doinquiry.css
  src/common/inquiry/css/storeInquiryEnter.css
Labels: feature

#51 [FEATURE][Signup]회원가입(미완성)
  .env
  package-lock.json
  package.json
  public/images/signup/default.png
  public/images/signup/on.png
  src/user/pages/signup/css/Signup.css
  src/user/pages/signup/pages/Signup.js
Labels: feature

#53 [FEATURE][StoreDetail] 프로필 불러오기, 지도 API 구현
  .gitignore
  package-lock.json
  package.json
  public/index.html
  src/common/floatingBar/css/floatingbar.module.css
  src/common/floatingBar/css/floatingbar.module.scss
  src/common/footer/css/footer.module.css
  src/user/pages/main/css/main.css
  src/user/pages/storedetail/components/Banner.js
  src/user/pages/storedetail/components/KakaoMap.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/profile.module.css.map
  src/user/pages/storedetail/css/profile.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/images/mapMarker-logo.png
  src/user/pages/storedetail/images/mapPointer-logo.png
  src/user/pages/storedetail/images/smallMapMarker-logo.png
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#54 [FEATURE][Inquiry] 문의 리스트 반응형 및 수정
  src/common/inquiry/components/StoreInquiryList.js
  src/common/inquiry/css/StoreInquiryList.css
  src/common/inquiry/css/doinquiry.css
Labels: feature, fix

#58 [FEATURE][mainFront] 메인페이지 프론트
  src/common/floatingBar/css/floatingbar.module.css
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.css.map
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.css.map
  src/user/pages/main/component/Map.js
  src/user/pages/main/component/Map.scss
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/banner.module.css.map
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/profile.module.css.map
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature

#59 [FEATURE][StoreDetail] 가게 상세페이지 상세운영시간, 카카오맵 오버레이
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#65 [FEATURE][Inquiry] 가게문의상세 반응형
  src/common/inquiry/components/AgreementModal.js
  src/common/inquiry/components/ResultSmallModal.js
  src/common/inquiry/components/StoreDoInquiry.js
  src/common/inquiry/components/StoreInquiryInfo.js
  src/common/inquiry/components/StoreInquiryList.js
  src/common/inquiry/components/StoreUpdateInquiry.js
  src/common/inquiry/components/UserDoInquiry.js
  src/common/inquiry/css/AgreementModal.css
  src/common/inquiry/css/StoreInquiryInfo.css
  src/common/inquiry/css/StoreInquiryInfoMiddle.css
  src/common/inquiry/css/StoreInquiryInfoSmall.css
  src/common/inquiry/css/doinquiry.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature

#62 [FEATURE][Login]로그인
  src/App.js
  src/common/authContext/RefreshToken.js
  src/common/authContext/useAuth.js
  src/common/logoutButton/components/Logout.js
  src/common/logoutButton/css/logout.css
  src/user/pages/login/api/.js
  src/user/pages/login/components/.js
  src/user/pages/login/css/Login.css
  src/user/pages/login/css/reset.css
  src/user/pages/login/css/reset.css.map
  src/user/pages/login/css/reset.scss
  src/user/pages/login/pages/Login.js
Labels: feature

#76 [FEATURE][StoreDetail] 가게 상세 페이지 달력 구현
  src/user/pages/storedetail/components/Banner.js
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.scss
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/images/todayIcon.png
  src/user/pages/storedetail/pages/ReservationInfo.js
Labels: feature

#78 [FEATURE][StoreDetail] 가게 상세 페이지 달력 today 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.scss
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.scss
  src/user/pages/login/css/reset.css
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/ReservationInfo.js
Labels: feature

#82 [FEATURE][QR] 예약확인 QR페이지
  public/images/qrcheck/missMatch.png
  public/images/qrcheck/qrCheckDefaultImg.png
  public/images/qrcheck/successConfirm.png
  src/App.js
  src/store/pages/qrCheck/api/QrInfoAPI.js
  src/store/pages/qrCheck/components/ExistenxeQr.js
  src/store/pages/qrCheck/components/NotFoundQr.js
  src/store/pages/qrCheck/css/QrCheck.css
  src/store/pages/qrCheck/css/QrConfirm.css
  src/store/pages/qrCheck/pages/QrCheck.js
  src/store/pages/qrCheck/pages/QrConfirm.js
  src/store/pages/qrCheck/router/QrRouter.js
Labels: feature

#84 [CHORE][AddJwtDecodeDependency]JWT 토큰 디코딩 의존성 추가
  package-lock.json
  package.json
Labels: chore

#87 [FIX][Inquiry] 문의 플로팅버튼 연결 및 정리
  public/images/inquiry/loadingInquiryList.gif
  src/App.js
  src/common/floatingBar/components/FloatingBar.js
  src/common/inquiry/components/StoreDoInquiry.js
  src/common/inquiry/components/StoreInquiryInfo.js
  src/common/inquiry/components/StoreInquiryList.js
  src/common/inquiry/components/StoreReportInfo.js
  src/common/inquiry/components/StoreUpdateInquiry.js
  src/common/inquiry/components/StoreUpdateReport.js
  src/common/inquiry/components/UserDoInquiry.js
  src/common/inquiry/css/StoreInquiryInfo.css
  src/common/inquiry/css/StoreInquiryList.css
  src/common/inquiry/css/doinquiry.css
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
Labels: fix

#64 [FEATURE][mainMyLocation] 메인페이지 지도 내위치 찾기
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/main/image/store1.png
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature

#75 [FEATURE][LocationAndRoulette] 메인페이지 내위치, 랜덤 룰렛
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/user/pages/main/Main.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
Labels: feature

#96 [FEATURE][StoreDetail] 가게 상세 페이지 예약 가능 시간 구현
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.scss
  src/user/pages/main/css/main.css
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/ReservationInfo.js
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#99 [FIX][Noshow]백엔드 노쇼 로직을 위한 약간의 수정
  package-lock.json
Labels: fix

#102 [FEATURE][ADMIN] 관리자 기본 레이아웃 및 폴더 세팅
  public/images/admin/header/adminHeaderLogo.png
  public/images/admin/navbar/dashboard.png
  public/images/admin/navbar/inquiry.png
  public/images/admin/navbar/notice.png
  public/images/admin/navbar/reservation.png
  public/images/admin/navbar/review.png
  public/images/admin/navbar/store.png
  public/images/admin/navbar/user.png
  src/App.js
  src/admin/components/AdminHeader.js
  src/admin/components/AdminNavBar.js
  src/admin/components/css/AdminHeader.css
  src/admin/components/css/AdminNavBar.css
  src/admin/layouts/AdminLayout.js
  src/admin/layouts/css/AdminLayout.css
  src/admin/pages/dashboard/api/.js
  src/admin/pages/dashboard/components/.js
  src/admin/pages/dashboard/css/.js
  src/admin/pages/dashboard/pages/AdminDashboard.js
  src/admin/pages/inquiry/api/.js
  src/admin/pages/inquiry/components/.js
  src/admin/pages/inquiry/css/.js
  src/admin/pages/inquiry/pages/AdminInquiry.js
  src/admin/pages/notice/api/.js
  src/admin/pages/notice/components/.js
  src/admin/pages/notice/css/.js
  src/admin/pages/notice/pages/AdminNotice.js
  src/admin/pages/reservation/api/.js
  src/admin/pages/reservation/components/.js
  src/admin/pages/reservation/css/.js
  src/admin/pages/reservation/pages/AdminReservation.js
  src/admin/pages/review/api/.js
  src/admin/pages/review/components/.js
  src/admin/pages/review/css/.js
  src/admin/pages/review/pages/AdminReview.js
  src/admin/pages/store/api/.js
  src/admin/pages/store/components/.js
  src/admin/pages/store/css/.js
  src/admin/pages/store/pages/AdminStore.js
  src/admin/pages/user/api/.js
  src/admin/pages/user/components/.js
  src/admin/pages/user/css/.js
  src/admin/pages/user/pages/AdminUser.js
  src/admin/route/AdminRoutes.js
  src/store/pages/qrCheck/routes/QrRoutes.js
Labels: feature

#106 [FEATURE][MainPage] 메인페이지 반응형, 수정
  public/index.html
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/reset.module.css.map
  src/common/header/css/header.css.map
  src/common/header/css/reset.css.map
  src/common/inquiry/css/reset.css.map
  src/common/reset/reset.css.map
  src/user/layouts/css/userlayout.module.css.map
  src/user/pages/info/css/Info.scss
  src/user/pages/login/css/Login.css
  src/user/pages/login/css/reset.css.map
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.css.map
  src/user/pages/main/component/Map.scss
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/signup/css/Signup.css
  src/user/pages/signup/css/reset.css.map
  src/user/pages/storedetail/css/banner.module.css.map
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/profile.module.css.map
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature, fix

#110 [FIX][Layout] 레이아웃 수정
  src/common/footer/css/footer.module.css
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
  src/user/layouts/css/userlayout.module.css.map
  src/user/layouts/css/userlayout.module.scss
  src/user/pages/main/component/Map.scss
Labels: fix

#111 [FEATURE][ADMIN] 관리자 대시보드
  package-lock.json
  package.json
  src/admin/layouts/AdminLayout.js
  src/admin/pages/dashboard/api/DashboardAPI.js
  src/admin/pages/dashboard/api/WeeklyResAPI.js
  src/admin/pages/dashboard/components/WeeklyRes.js
  src/admin/pages/dashboard/css/AdminDashboard.css
  src/admin/pages/dashboard/pages/AdminDashboard.js
Labels: feature

#113 [FEATURE][MainPage] 메인페이지 프론트 완성
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.css.map
  src/user/pages/main/component/Map.scss
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
Labels: feature

#116 [FEATURE][SearchPage]검색 페이지 프론트
  package-lock.json
  src/App.js
  src/common/header/components/Header.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css.map
  src/user/pages/main/component/Map.js
  src/user/pages/main/component/Map.scss
  src/user/pages/search/Search.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/banner.module.css.map
  src/user/pages/storedetail/css/banner.module.scss
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/menu.module.scss
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
Labels: feature, fix

#122 [FIX][FixCSS]CSS 모듈화
  src/user/pages/login/css/Login.module.css
  src/user/pages/login/pages/Login.js
  src/user/pages/signup/css/Signup.module.css
  src/user/pages/signup/pages/Signup.js
Labels: fix

#127 [FEATURE][StoreDetail] 가게 상세 페이지 리뷰 작성하기 레이아웃
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.scss
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/UserStorePage.js
Labels: feature

#131 [FIX][FixAllCSS]CSS 전반적으로 전체 수정
  .github/team_rules/team_rules/team_rules.md
  package-lock.json
  src/user/pages/find/css/Find.module.css
  src/user/pages/find/pages/Find.js
  src/user/pages/login/css/Login.module.css
  src/user/pages/login/pages/Login.js
  src/user/pages/signup/css/Signup.module.css
Labels: fix

#136 [FEATURE][searchPage] 검색 페이지 반응형 완성
  src/user/layouts/UserLayout.js
  src/user/layouts/css/userlayout.module.css
  src/user/pages/find/css/reset.css.map
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/search/Search.js
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/search/image/banner.png
  src/user/pages/search/image/image-1.png
  src/user/pages/search/image/image-2.png
  src/user/pages/search/image/image.png
  src/user/pages/search/image/image3.png
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature, fix

#137 [FEATURE][ADMIN] 관리자 대시보드 그래프
  src/admin/pages/dashboard/api/DashboardAPI.js
  src/admin/pages/dashboard/components/MonthlyNoshow.js
  src/admin/pages/dashboard/components/MonthlyStores.js
  src/admin/pages/dashboard/components/TodayRes.js
  src/admin/pages/dashboard/components/TotalStores.js
  src/admin/pages/dashboard/components/WeeklyRes.js
  src/admin/pages/dashboard/css/AdminDashboard.css
  src/admin/pages/dashboard/pages/AdminDashboard.js
Labels: feature
