Repository Solving-Our-Meals/ukki-front, pull requests merged in 2025-02, with the labels that each got.

#518 [FIX][StoreDetail] 예약 날짜 선택 오류
  src/store/layouts/css/bosslayout.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.scss
  src/user/pages/reservation/components/ReservationInfo.js
  src/user/pages/storedetail/components/Calendar.js
Labels: bug, fix

#520 [FIX][WEB] 도메인 변경으로 인한 url변경
  src/config/api.config.js
Labels: fix

#526 [FEATURE][MAIN] 메인페이지 반응형
  package-lock.json
  package.json
  src/common/header/css/header.css
  src/config/api.config.js
  src/store/layouts/BossLayout.js
  src/store/pages/bossInquiry/css/totalInquiryPage.module.css
  src/store/pages/bossInquiry/css/totalInquiryPage.module.css.map
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css.map
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.css.map
  src/user/pages/main/Main.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/reservation/css/representativePhoto.module.css.map
  src/user/pages/reservation/css/termsOfUse.module.css.map
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/review.module.css.map
Labels: feature

#527 [Merge][ForUpdate] 우끼 업데이트
  package-lock.json
  package.json
  src/admin/pages/reservation/pages/ReservationTodayInfo.js
  src/admin/pages/store/pages/StoreInfo.js
  src/admin/pages/store/pages/StoreInfoRegist.js
  src/common/header/css/header.css
  src/common/inquiry/components/DoInquiry.js
  src/config/api.config.js
  src/store/layouts/BossLayout.js
  src/store/layouts/css/bosslayout.module.css
  src/store/pages/bossInquiry/css/totalInquiryPage.module.css
  src/store/pages/bossInquiry/css/totalInquiryPage.module.css.map
  src/store/pages/bossInquiry/pages/TotalInquiryPage.js
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css.map
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.css.map
  src/store/pages/bossNotice/css/bossTotalNotice.module.scss
  src/store/pages/qrCheck/pages/QrCheck.js
  src/user/pages/main/Main.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/reservation/components/ReservationInfo.js
  src/user/pages/reservation/css/representativePhoto.module.css.map
  src/user/pages/reservation/css/termsOfUse.module.css.map
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/pages/Review.js
Labels: merge

#529 [FIX][StoreDetail] api 오류 / 파라미터 오류 등등 수정
  src/store/pages/bossInquiry/components/SpecificReviewModal.js
  src/store/pages/bossReview/components/SpecificReview.js
  src/store/pages/bossReview/pages/TotalReview.js
  src/user/pages/storedetail/pages/Review.js
Labels: fix

#531 [FIX][SomeFix]글구 수정
  src/user/pages/signup/pages/Signup.js
Labels: fix, chore

#535 [FEATURE][ALL] 반응형
  src/common/header/components/BossHeader.js
  src/common/header/components/Header.js
  src/common/header/css/bossHeader.module.css
  src/common/header/css/bossHeader.module.scss
  src/common/header/css/header.css
  src/common/header/css/header.scss
  src/common/inquiry/components/DoInquiry.js
  src/config/api.config.js
  src/store/pages/bossInquiry/css/specificInquiry.module.css
  src/store/pages/bossInquiry/css/specificInquiry.module.css.map
  src/store/pages/bossNotice/css/bossTotalNotice.module.css.map
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/storedetail/components/Menu.js
Labels: feature

#536 [Merge][ForUpdate] 우끼 업데이트
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  README.md
  src/admin/pages/reservation/pages/ReservationEndInfo.js
  src/admin/pages/reservation/pages/ReservationTodayInfo.js
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreInfo.js
  src/common/header/components/BossHeader.js
  src/common/header/components/Header.js
  src/common/header/css/bossHeader.module.css
  src/common/header/css/bossHeader.module.scss
  src/common/header/css/header.css
  src/common/header/css/header.scss
  src/common/inquiry/components/DoInquiry.js
  src/config/api.config.js
  src/store/pages/bossInquiry/components/SpecificReviewModal.js
  src/store/pages/bossInquiry/css/specificInquiry.module.css
  src/store/pages/bossInquiry/css/specificInquiry.module.css.map
  src/store/pages/bossNotice/css/bossTotalNotice.module.css.map
  src/store/pages/bossReview/components/SpecificReview.js
  src/store/pages/bossReview/pages/TotalReview.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/signup/pages/Signup.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/pages/Review.js
Labels: merge

#538 [FIX][FixLoading]로딩 추가
  src/config/api.config.js
  src/user/pages/mypage/pages/Reservation.js
Labels: fix

#540 [FIX][ADMIN] 관리자 기능 개선
  src/admin/pages/dashboard/css/AdminDashboard.css
  src/admin/pages/inquiry/api/StoreNoAPI.js
  src/admin/pages/inquiry/css/Inquiry.module.css
  src/admin/pages/inquiry/pages/InquiryInfo.js
  src/admin/pages/inquiry/pages/ReportInfo.js
Labels: fix

#542 [FEATURE][ALL] 반응형
  src/common/footer/css/footer.module.scss
  src/store/pages/bossStore/components/WeeklyReservationGraph.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/announcement/components/SpecificNotice.js
  src/user/pages/announcement/components/TotalNotice.js
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/specificNotice.module.css.map
  src/user/pages/announcement/css/specificNotice.module.scss
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css.map
  src/user/pages/announcement/css/totalNotice.module.scss
  src/user/pages/info/Info.js
  src/user/pages/info/css/Info.css
  src/user/pages/info/css/Info.css.map
  src/user/pages/info/css/Info.scss
  src/user/pages/info/css/footer.module.css
  src/user/pages/info/css/footer.module.css.map
  src/user/pages/info/css/footer.module.scss
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/footer.module.css.map
  src/user/pages/main/css/footer.module.scss
  src/user/pages/search/Search.js
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/footer.module.css.map
  src/user/pages/search/css/footer.module.scss
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/footer.module.css.map
  src/user/pages/storedetail/css/footer.module.scss
Labels: feature

#546 [FIX][FixForComplement]보완 사항
  package-lock.json
  src/App.js
  src/common/authContext/PrivateRoute.js
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/ReviewDetail.js
Labels: bug, fix

#549 [FIX][Total] 전반적인 오류 수정
  src/store/pages/bossInquiry/pages/SpecificInquiry.js
  src/user/pages/storedetail/pages/Review.js
Labels: bug, fix

#551 [FIX][ALL] 맵 수정
  src/config/api.config.js
  src/user/pages/main/component/Map.js
Labels: fix

#553 [MERGE][ForUpdate]
  src/config/api.config.js
Labels: merge

#555 [FIX][FixLogout]로그아웃 수정
  src/admin/components/AdminHeader.js
  src/common/header/components/BossHeader.js
  src/common/header/components/Header.js
  src/user/pages/mypage/pages/ReviewDetail.js
Labels: bug, fix

#557 [FIX][BOSS] 사장님 페이지 에러
  src/App.js
  src/common/header/components/BossHeader.js
  src/config/api.config.js
  src/store/pages/bossStore/pages/BossPage.js
Labels: fix

#558 [FIX][BOSS] 사장님 페이지 에러2
  src/store/pages/bossStore/components/BasicTimePicker.js
  src/store/pages/bossStore/pages/BossPage.js
Labels: fix

#563 [FIX][BUG] 카카오 api 전달
  src/common/error/css/error403.module.css
  src/common/error/css/error404.module.css
  src/common/error/css/error500.module.css
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/bossHeader.module.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/config/api.config.js
  src/store/pages/bossInquiry/css/specificInquiry.module.css
  src/store/pages/bossInquiry/css/specificReviewModal.module.css
  src/store/pages/bossReview/css/specificReview.module.css
  src/store/pages/bossReview/css/totalReview.module.css
  src/store/pages/storeInfo/css/bossBanner.module.css
  src/store/pages/storeInfo/css/bossMenu.module.css
  src/store/pages/storeInfo/css/bossProfile.module.css
  src/store/pages/storeInfo/css/bossStoreInfoPage.module.css
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/info/css/footer.module.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/userStorePage.module.css
Labels: bug, fix

#570 [FIX][MAIN] 메인페이지 수정
  src/config/api.config.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
Labels: fix

#571 [FIX][FixLogout]로그아웃 수정
  src/common/header/components/Header.js
Labels: bug, fix

#572 [MERGE][ForUpdate]우끼 업데이트
  src/common/header/components/Header.js
  src/config/api.config.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
Labels: bug, fix

#574 [FIX][CSS] css 수정
  src/admin/pages/inquiry/pages/InquiryList.js
  src/admin/pages/reservation/pages/ReservationList.js
  src/admin/pages/review/pages/ReviewList.js
  src/admin/pages/store/pages/StoreList.js
  src/admin/pages/user/pages/UserList.js
  src/user/pages/main/Main.js
  src/user/pages/mypage/css/MyProfile.module.css
  src/user/pages/mypage/css/Mypage.module.css
  src/user/pages/storedetail/pages/StoreDetail.js
  src/user/pages/storedetail/pages/UserStorePage.js
Labels: fix

#581 [FIX][ETC] 간단한 수정
  src/common/inquiry/css/doinquiry.css
Labels: fix

#579 [FIX][SCSS] 헤더 수정
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
Labels: fix

#583 [FIX][CSS] 약간의 수정
  package-lock.json
  src/admin/pages/review/pages/ReviewInfo.js
  src/admin/pages/store/css/StoreEdit.module.css
  src/admin/pages/store/css/StoreInfo.module.css
  src/admin/pages/store/css/StoreInfoRegist.module.css
Labels: fix

#584 [MERGE][ForUpdate] 우끼 업데이트
  package-lock.json
  src/admin/pages/review/pages/ReviewInfo.js
  src/admin/pages/store/css/StoreEdit.module.css
  src/admin/pages/store/css/StoreInfo.module.css
  src/admin/pages/store/css/StoreInfoRegist.module.css
Labels: merge

#586 [FIX][HEADER] 헤더 수정
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/config/api.config.js
Labels: fix

#587 [MERGE][ForUpdate] 우끼 업데이트
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/config/api.config.js
Labels: merge

#588 [FIX][INFO] 인포 수정
  src/user/pages/info/Info.js
Labels: fix

#589 [MERGE][ForUpdate] 우끼 업데이트
  src/config/api.config.js
  src/user/pages/info/Info.js
Labels: merge

#591 [FIX][ETC] 약간의 수정
  src/admin/pages/inquiry/pages/InquiryList.js
  src/admin/pages/review/pages/ReviewInfo.js
  src/admin/pages/review/pages/ReviewList.js
Labels: fix

#592 [MERGE][ForUpdate] 우끼 업데이트
  README.md
  src/admin/pages/inquiry/pages/InquiryList.js
  src/admin/pages/review/pages/ReviewInfo.js
  src/admin/pages/review/pages/ReviewList.js
Labels: merge
