Repository Solving-Our-Meals/ukki-front, pull requests merged in 2025-01, with the labels that each got.

#142 [FEATURE][ADMIN] 관리자 대시보드 완료
  src/admin/components/css/AdminNavBar.css
  src/admin/layouts/css/AdminLayout.css
  src/admin/pages/dashboard/api/DashboardAPI.js
  src/admin/pages/dashboard/components/MonthlyNoshow.js
  src/admin/pages/dashboard/components/MonthlyStores.js
  src/admin/pages/dashboard/components/ProcessingInquiry.js
  src/admin/pages/dashboard/components/TodayRes.js
  src/admin/pages/dashboard/components/WeeklyRes.js
  src/admin/pages/dashboard/css/AdminDashboard.css
  src/admin/pages/dashboard/css/WeeklyRes.css
  src/admin/pages/dashboard/css/reset.css
  src/admin/pages/dashboard/pages/AdminDashboard.js
  src/user/pages/mypage/pages/MyProfile.js
Labels: feature

#144 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 등록하기 구현
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/createReview.module.scss
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/Review.js
Labels: feature

#146 [FIX][FixJwtToken]토큰에 정보 안담기던 문제 해결
  package-lock.json
  src/user/pages/mypage/css/MyProfile.module.css
  src/user/pages/mypage/css/Tabs.module.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/mypage/css/reset.css.map
  src/user/pages/mypage/css/reset.scss
  src/user/pages/mypage/pages/MyProfile.js
  src/user/pages/mypage/pages/MypageMain.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/Tabs.js
Labels: fix

#155 [FIX][FixRefreshToken]리프레시 토큰 갱신 기능 추가 및 문제 해결
  package-lock.json
  src/App.js
  src/common/authContext/AuthContext.js
  src/common/authContext/RefreshToken.js
  src/common/authContext/useAuth.js
  src/user/pages/login/pages/Login.js
Labels: feature, fix

#157 [FEATURE][StoreDetail] 가게 상세페이지 반응형 CSS
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/css/banner.module.css.map
  src/user/pages/storedetail/css/banner.module.scss
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css.map
  src/user/pages/storedetail/css/kakaoMap.module.scss
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.scss
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
Labels: feature

#159 [Feature][MainFix] 메인페이지 수정
  package-lock.json
  public/index.html
  src/common/floatingBar/css/floatingbar.module.css.map
  src/common/footer/css/footer.module.css
  src/common/footer/css/footer.module.css.map
  src/common/footer/css/footer.module.scss
  src/common/footer/css/reset.module.css.map
  src/common/header/css/header.css.map
  src/common/header/css/reset.css.map
  src/common/inquiry/css/reset.css.map
  src/common/reset/reset.css.map
  src/user/pages/find/css/reset.css.map
  src/user/pages/login/css/reset.css.map
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css.map
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/main/image/roulette.png
  src/user/pages/mypage/css/reset.css.map
  src/user/pages/search/css/search.module.css.map
  src/user/pages/signup/css/reset.css.map
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/kakaoMap.module.css.map
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/profile.module.css.map
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
Labels: feature, fix

#172 [FEATURE][MainLoaction] 현재 위치 검색, 입력
  .vscode/settings.json
  src/common/header/components/Header.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/main/image/marker.png
  src/user/pages/reservation/css/termsOfUse.module.css.map
Labels: feature

#174 [FIX][StoreDetail] 캘린더 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/mypage/pages/MyProfile.js
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.scss
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
Labels: fix

#177 [FEATURE][ADMIN] 회원 수정 및 삭제
  package-lock.json
  src/admin/components/AdminAgreementModal.js
  src/admin/components/AdminResultModal.js
  src/admin/components/css/AgreementModal.css
  src/admin/components/css/reset.css
  src/admin/pages/user/css/UserInfo.module.css
  src/admin/pages/user/pages/UserConfirmModal.js
  src/admin/pages/user/pages/UserInfo.js
  src/admin/pages/user/pages/UserResultModal.js
Labels: feature

#175 [FIX][SomeFix]링크수정 및 의존성 제거
  package-lock.json
  package.json
  src/user/pages/mypage/pages/MyProfile.js
Labels: bug, fix

#182 [FIX][StoreDetail] 가게 상세페이지 전체적인 수정
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/pages/ReservationInfo.js
  src/user/pages/storedetail/pages/StoreDetail.js
  src/user/pages/storedetail/pages/UserStorePage.js
Labels: fix

#185 [FIX][Header] 헤더 scss 변경
  package-lock.json
  public/index.html
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.css
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.css.map
  src/user/pages/main/css/main.scss
  src/user/pages/main/image/name-bg.png
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
Labels: feature, fix

#186 [FIX][ADMIN] 회원 수정사항
  package-lock.json
  src/admin/pages/store/pages/AdminStore.js
  src/admin/pages/user/api/UserListAPI.js
  src/admin/pages/user/css/UserInfo.module.css
  src/admin/pages/user/css/UserList.module.css
  src/admin/pages/user/pages/UserInfo.js
  src/admin/pages/user/pages/UserList.js
  src/admin/route/AdminRoutes.js
Labels: fix

#189 [FIX][FixCssForFirefox]파이어폭스 전용 CSS 수정(크로스웹)
  src/user/pages/find/css/Find.module.css
  src/user/pages/login/css/Login.module.css
  src/user/pages/signup/css/Signup.module.css
Labels: bug, fix, chore

#200 [FIX][StoreDetail] 가게 상세페이지 수정사항 + 리뷰 작성 권한 부여
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/menu.module.scss
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/css/storedetail.module.scss
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature, fix

#201 [FEATURE][ADMIN] 가게 수정 페이지
  package-lock.json
  src/admin/pages/store/api/AddrToCoordinate.js
  src/admin/pages/store/css/StoreEdit.module.css
  src/admin/pages/store/css/StoreInfo.module.css
  src/admin/pages/store/css/menu.module.css
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreInfo.js
Labels: feature

#207 [FIX][FixCSS]전역 설정 관련 CSS 수정
  package-lock.json
  src/user/pages/find/css/Find.module.css
Labels: feature, chore

#218 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 별점 및 리뷰 작성 권한 여부
  src/user/pages/reservation/components/Profile.js
  src/user/pages/reservation/components/RepresentativePhoto.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/createReview.module.scss
  src/user/pages/storedetail/css/menu.module.css.map
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css.map
  src/user/pages/storedetail/images/Star Filled.png
  src/user/pages/storedetail/images/nonePhotoReview.png
  src/user/pages/storedetail/pages/Review.js
Labels: feature

#222 [FEATURE][ADMIN] 가게 수정 삭제
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreInfo.js
Labels: feature

#226 [FEATURE][Main] 메인페이지 완성
  package-lock.json
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/main/css/main.css
  src/user/pages/main/css/main.scss
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
Labels: feature

#229 [FIX][StoreDetail] 가게 상세페이지 리뷰 레이아웃 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/layouts/css/userlayout.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/components/KakaoMap.js
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/KakaoMap.js
  src/user/pages/storedetail/components/calendar_backup_file.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.scss
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/StoreDetail.js
  src/user/pages/storedetail/pages/UserStorePage.js
Labels: fix

#240 [FEATURE][DeleteModal]리뷰 삭제 상태 완료 모달
  public/images/mypage/profile/notInfo.png
  src/user/pages/mypage/css/Reservation.module.css
  src/user/pages/mypage/css/Review.module.css
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/Review.js
Labels: feature

#243 [FIX][StoreDetail] 가게 상세페이지 배너, 리뷰 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/createReview.module.css.map
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/profile.module.css.map
  src/user/pages/storedetail/css/profile.module.scss
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/reservation.module.css.map
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/Review.js
Labels: fix

#247 [FEATURE][ADMIN] 예약 상세조회 및 삭제
  src/admin/pages/reservation/api/ReservationEndInfoAPI.js
  src/admin/pages/reservation/api/ReservationListAPI.js
  src/admin/pages/reservation/api/ReservationTodayInfoAPI.js
  src/admin/pages/reservation/css/ReservationInfo.module.css
  src/admin/pages/reservation/css/ReservationList.module.css
  src/admin/pages/reservation/pages/AdminReservation.js
  src/admin/pages/reservation/pages/ReservationEndInfo.js
  src/admin/pages/reservation/pages/ReservationList.js
  src/admin/pages/reservation/pages/ReservationTodayInfo.js
  src/admin/pages/store/api/GetBannerAPI.js
  src/admin/pages/store/css/StoreList.module.css
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreList.js
  src/admin/pages/user/css/UserList.module.css
  src/admin/pages/user/pages/UserList.js
  src/admin/route/AdminRoutes.js
Labels: feature

#252 [FEATURE][SEARCH] 검색어 자동완성 및 실시간 인기 검색어 구현
  src/user/pages/search/Search.js
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/storedetail/css/review.module.css.map
Labels: feature

#257 [FEATURE][StoreDetail] 가게 상세페이지 리뷰 삭제 완성
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.scss
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/pages/Review.js
Labels: feature

#259 [FIX][StoreDetail] 가게 상세페이지 달력 수정
  package-lock.json
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/review.module.css.map
  src/user/pages/storedetail/css/storedetail.module.css
Labels: bug, fix

#260 [FEATURE][MypageInquiryDetails]마이페이지 문의 상세페이지
  package-lock.json
  public/images/common/logo.png
  src/user/pages/mypage/api/getUserInfo.js
  src/user/pages/mypage/css/Inquiry.module.css
  src/user/pages/mypage/css/Review.module.css
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/InquiryDetails.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/Review.js
  src/user/pages/mypage/route/Mypage.js
Labels: feature

#269 [FEATURE][ADMIN] 리뷰 상세보기
  src/admin/pages/review/api/ReviewInfoAPI.js
  src/admin/pages/review/css/ReviewInfo.module.css
  src/admin/pages/review/pages/ReviewInfo.js
  src/admin/pages/review/pages/ReviewList.js
  src/admin/route/AdminRoutes.js
Labels: feature

#278 [FIX][HEADER] 헤더 수정
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/user/pages/search/Search.js
Labels: fix

#284 [FIX][ADMIN] 가게 이미지 fetch조정
  src/admin/pages/store/api/GetBannerAPI.js
  src/admin/pages/store/api/GetMenuAPI.js
  src/admin/pages/store/api/GetProfileAPI.js
  src/admin/pages/store/components/Banner.js
  src/admin/pages/store/components/Menu.js
  src/admin/pages/store/components/Profile.js
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreInfo.js
Labels: fix

#286 [FIX][FixMypageFeedback]마이페이지 피드백 수정
  src/user/pages/mypage/css/Inquiry.module.css
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/InquiryDetails.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/Review.js
  src/user/pages/mypage/route/Mypage.js
Labels: bug, fix

#290 [FIX][SEARCH] 검색페이지 수정
  src/common/header/components/Header.js
  src/common/header/css/header.css
  src/common/header/css/header.css.map
  src/common/header/css/header.scss
  src/user/pages/search/Search.js
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
Labels: fix

#293 [FEATURE][MypageInquiryModal]마이페이지 문의 모달
  package-lock.json
  src/user/pages/mypage/css/Inquiry.module.css
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/InquiryDetails.js
Labels: feature

#296 [FEATURE][BOSSPAGE] 사장님 페이지 레이아웃 짜기
  src/store/pages/bossStore/pages/.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
  src/user/pages/search/Search.js
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
Labels: feature

#305 [FIX][BossNotice] 사장님 공지사항 검색 기능 API 수정
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/store/pages/bossNotice/components/BossTotalNotice.js
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
Labels: fix

#310 [FEATURE][ADMIN] 문의 조회, 수정, 삭제
  package-lock.json
  src/admin/pages/inquiry/api/ReportInfoAPI.js
  src/admin/pages/inquiry/css/Inquiry.module.css
  src/admin/pages/inquiry/css/InquiryList.module.css
  src/admin/pages/inquiry/pages/InquiryInfo.js
  src/admin/pages/inquiry/pages/InquiryList.js
  src/admin/pages/inquiry/pages/ReportInfo.js
Labels: feature

#313 [FIX][Footer] 푸터 위치 수정
  src/common/header/css/header.css.map
  src/user/pages/info/Info.js
  src/user/pages/info/component/Footer.js
  src/user/pages/info/css/footer.module.css
  src/user/pages/info/css/footer.module.css.map
  src/user/pages/info/css/footer.module.scss
  src/user/pages/info/image/footer-logo.png
  src/user/pages/main/Main.js
  src/user/pages/main/component/Footer.js
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/footer.module.css.map
  src/user/pages/main/css/footer.module.scss
  src/user/pages/main/image/footer-logo.png
  src/user/pages/search/Search.js
  src/user/pages/search/components/Footer.js
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/footer.module.css.map
  src/user/pages/search/css/footer.module.scss
  src/user/pages/search/css/search.module.css
  src/user/pages/search/css/search.module.css.map
  src/user/pages/search/css/search.module.scss
  src/user/pages/search/image/footer-logo.png
  src/user/pages/storedetail/components/Footer.js
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/footer.module.css.map
  src/user/pages/storedetail/css/footer.module.scss
  src/user/pages/storedetail/css/userStorePage.module.css
  src/user/pages/storedetail/css/userStorePage.module.css.map
  src/user/pages/storedetail/css/userStorePage.module.scss
  src/user/pages/storedetail/images/footer-logo.png
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/UserStorePage.js
Labels: fix

#321 [FEATURE][ADMIN] 공지사항 생성, 수정, 삭제
  package-lock.json
  src/admin/pages/notice/css/NoticeInfo.module.css
  src/admin/pages/notice/css/NoticeRegist.module.css
  src/admin/pages/notice/pages/NoticeInfo.js
  src/admin/pages/notice/pages/NoticeRegist.js
  src/admin/route/AdminRoutes.js
Labels: feature

#323 [FIX][Footer] Footer 레이아웃 수정
  src/common/error/css/error403.module.css
  src/common/error/css/error404.module.css
  src/common/error/css/error500.module.css
  src/user/pages/info/css/footer.module.css
  src/user/pages/info/css/footer.module.scss
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/footer.module.scss
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/footer.module.scss
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/footer.module.scss
  src/user/pages/storedetail/css/userStorePage.module.css
Labels: fix

#329 [FEATURE][MypageInquiryFiles]마이페이지 문의 첨부 기능 추가, 마이페이지 리뷰 삭제 로직 추가, 마이페이지 프로필 CSS 에러 수정
  package-lock.json
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/css/MyProfile.module.css
  src/user/pages/mypage/pages/Review.js
Labels: bug, feature, fix

#338 [FEATURE][BOSSPAGE] 사장님 페이지 예약 프론트 구현
  src/App.js
  src/common/authContext/AuthContext.js
  src/common/authContext/PrivateRoute.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
  src/user/pages/search/Search.js
Labels: feature

#339 [FEATURE][MypageInquiryFiles]마이페이지 문의 파일 다운로드 시 기존 파일 제거 로직 및 다운로드 로직 추가
  src/user/pages/mypage/pages/InquiryDetails.js
Labels: feature, fix

#346 [FIX][BossNotice] 사장님 페이지 공지사항 상세 수정 레이아웃 변경
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/store/layouts/BossLayout.js
  src/store/pages/bossNotice/components/BossSpecificNotice.js
  src/store/pages/bossNotice/components/BossTotalNotice.js
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css
  src/store/pages/bossNotice/css/bossSpecificNotice.module.scss
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.scss
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
Labels: fix

#357 [FIX][ADMIN] 가게 수정 시 주소 오류
  Dockerfile
  package-lock.json
  src/admin/pages/store/api/GetBannerAPI.js
  src/admin/pages/store/pages/StoreEdit.js
Labels: fix

#360 [FEATURE][BOSSMYPAGE] 사장님페이지 예약인원 조정 및 날짜 시간 선택
  package-lock.json
  package.json
  src/common/error/css/error403.module.css
  src/common/error/css/error404.module.css
  src/common/error/css/error500.module.css
  src/store/layouts/BossLayout.js
  src/store/pages/bossStore/components/Sidebar.js
  src/store/pages/bossStore/components/WeeklyReservationGraph.js
  src/store/pages/bossStore/css/BossPage.css
  src/store/pages/bossStore/css/Sidebar.css
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/info/css/footer.module.css
  src/user/pages/info/css/footer.module.css.map
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/footer.module.css.map
  src/user/pages/reservation/css/representativePhoto.module.css.map
  src/user/pages/search/Search.js
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/footer.module.css.map
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/footer.module.css.map
  src/user/pages/storedetail/css/userStorePage.module.css
Labels: feature

#366 [CHORE][MoveImages]이미지 파일 이동 및 임포트 설정
  package-lock.json
  src/admin/pages/user/pages/UserInfo.js
  src/store/layouts/BossLayout.js
  src/user/pages/find/pages/Find.js
  src/user/pages/login/pages/Login.js
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/images/badge1.png
  src/user/pages/mypage/images/badge2.png
  src/user/pages/mypage/images/badge3.png
  src/user/pages/mypage/images/badge4.png
  src/user/pages/mypage/images/badge5.png
  src/user/pages/mypage/images/badge6.png
  src/user/pages/mypage/images/mypage/default.png
  src/user/pages/mypage/images/mypage/info.png
  src/user/pages/mypage/images/mypage/logo.png
  src/user/pages/mypage/images/mypage/notInfo.png
  src/user/pages/mypage/images/mypage/password.png
  src/user/pages/mypage/images/mypage/pencil.gif
  src/user/pages/mypage/pages/Info.js
  src/user/pages/mypage/pages/InquiryDetails.js
  src/user/pages/mypage/pages/ProfileInfo.js
  src/user/pages/mypage/pages/ReviewDetail.js
  src/user/pages/mypage/route/Mypage.js
  src/user/pages/signup/images/default.png
  src/user/pages/signup/images/on.png
  src/user/pages/signup/images/signupLogo.png
  src/user/pages/signup/pages/Signup.js
Labels: chore

#375 [FEATURE][bossPage] 사장님 페이지 예약 날짜및 인원 조회
  package-lock.json
  package.json
  src/common/authContext/PrivateRoute.js
  src/store/pages/bossStore/components/BasicTimePicker.js
  src/store/pages/bossStore/pages/BossPage.js
Labels: feature

#393 [FEATURE][BOSSPAGE] 사장님 페이지 예약인원조정
  package-lock.json
  src/store/pages/bossStore/components/BasicTimePicker.js
  src/store/pages/bossStore/pages/BossPage.js
Labels: feature

#387 [FEATURE][SavePagination]페이지네이션 저장 기능
  src/user/pages/mypage/css/ReservationDetail.module.css
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/ReservationDetail.js
  src/user/pages/mypage/pages/Review.js
Labels: feature

#398 [FIX][FixDeleteAccount]회원 탈퇴 수정에 맞춰 부족한 부분 조정
  src/user/pages/mypage/pages/ProfileInfo.js
Labels: fix

#413 [FEATURE][BOSS] 사장님 페이지 시간별 예약 가능인원
  src/store/pages/bossStore/pages/BossPage.js
Labels: feature

#396 [FEATURE][BossInfo] 사장님 페이지 가게 상세 조회
  src/common/error/css/error403.module.css
  src/common/error/css/error404.module.css
  src/common/error/css/error500.module.css
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/header.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/store/pages/bossInquiry/css/specificInquiry.module.css
  src/store/pages/bossInquiry/css/totalInquiryPage.module.css
  src/store/pages/bossNotice/css/bossSpecificNotice.module.css
  src/store/pages/bossNotice/css/bossTotalNotice.module.css
  src/store/pages/bossReview/css/specificReview.module.css
  src/store/pages/bossReview/css/totalReview.module.css
  src/store/pages/storeInfo/css/bossBanner.module.css
  src/store/pages/storeInfo/css/bossBanner.module.scss
  src/store/pages/storeInfo/css/bossMenu.module.css
  src/store/pages/storeInfo/css/bossMenu.module.scss
  src/store/pages/storeInfo/css/bossProfile.module.css
  src/store/pages/storeInfo/css/bossProfile.module.scss
  src/store/pages/storeInfo/css/bossStoreInfoPage.module.css
  src/store/pages/storeInfo/css/bossStoreInfoPage.module.scss
  src/store/pages/storeInfo/page/BossStoreInfoPage.js
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/info/css/footer.module.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/createReview.module.css
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/userStorePage.module.css
Labels: feature

#415 [FEATURE][DEPLOY] 배포 업데이트
  .github/workflows/deploy.yml
  Dockerfile
  deploy.sh
  docker-compose.local.yml
  docker-compose.yml
  nginx.conf
  src/admin/pages/user/api/.js
  src/admin/pages/user/api/TotalUserAPI.js
  src/admin/pages/user/api/UserInfoAPI.js
  src/admin/pages/user/api/UserListAPI.js
  src/admin/pages/user/css/images/badge1.png
  src/admin/pages/user/css/images/badge2.png
  src/admin/pages/user/css/images/badge3.png
  src/admin/pages/user/css/images/badge4.png
  src/admin/pages/user/css/images/badge5.png
  src/admin/pages/user/css/images/badge6.png
  src/admin/pages/user/pages/UserInfo.js
  src/config/api.config.js
Labels: feature

#417 [FIX][FixForServerAndRerendering]서버 배포를 위한 수정 및 리렌더링 보완
  package-lock.json
  src/user/pages/mypage/pages/ProfileInfo.js
  src/user/pages/mypage/pages/Review.js
  src/user/pages/mypage/route/Mypage.js
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
Labels: bug, fix

#422 [FIX][BOSS] 오류 수정
  src/store/pages/bossStore/pages/BossPage.js
Labels: fix

#419 [FIX][Total] 사장님 페이지, 가게 상세페이지 오류 해결
  src/common/header/components/BossHeader.js
  src/user/layouts/UserLayout.js
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Profile.js
Labels: bug, fix

#425 [FIX][FixForServerDeployment]서버 배포 설정
  package-lock.json
  src/common/authContext/AuthContext.js
  src/config/api.config.js
  src/user/pages/find/css/Find.module.css
  src/user/pages/find/pages/Find.js
  src/user/pages/login/pages/Login.js
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/pages/Inquiry.js
  src/user/pages/mypage/pages/InquiryDetails.js
  src/user/pages/mypage/pages/ProfileInfo.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/ReservationDetail.js
  src/user/pages/mypage/pages/Review.js
  src/user/pages/mypage/pages/ReviewDetail.js
  src/user/pages/mypage/route/Mypage.js
  src/user/pages/signup/pages/Signup.js
Labels: fix

#428 [FEATURE][Total] 모든 API에 header 추가
  src/common/authContext/PrivateRoute.js
  src/config/api.config.js
  src/store/pages/bossInquiry/pages/SpecificInquiry.js
  src/store/pages/bossInquiry/pages/TotalInquiryPage.js
  src/store/pages/bossNotice/components/BossSpecificNotice.js
  src/store/pages/bossNotice/components/BossTotalNotice.js
  src/store/pages/bossReview/components/SpecificReview.js
  src/store/pages/bossReview/pages/TotalReview.js
  src/store/pages/storeInfo/components/BossBanner.js
  src/store/pages/storeInfo/components/BossMenu.js
  src/store/pages/storeInfo/components/BossProfile.js
  src/store/pages/storeInfo/page/BossStoreInfoPage.js
  src/user/pages/reservation/components/Profile.js
  src/user/pages/reservation/components/RepresentativePhoto.js
  src/user/pages/reservation/components/ReservationInfo.js
  src/user/pages/reservation/components/TermsOfUse.js
  src/user/pages/storedetail/components/Banner.js
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: feature

#436 [FIX][StoreDetail] 가게 상세페이지 리뷰 작성 및 그 외 버그
  src/config/api.config.js
  src/store/pages/bossInquiry/pages/SpecificInquiry.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/pages/Review.js
Labels: bug, fix

#438 [FIX][DEPLOY] deploy 수정
  .github/workflows/deploy.yml
Labels: fix

#451 [FIX][ADMIN] 관리자 css 개선 및 기능체크
  package-lock.json
  src/App.js
  src/admin/components/AdminHeader.js
  src/admin/components/css/AdminHeader.css
  src/admin/components/css/AdminNavBar.css
  src/admin/components/css/PopupCalendar.module.css
  src/admin/layouts/css/AdminLayout.css
  src/admin/pages/inquiry/pages/InquiryList.js
  src/admin/pages/notice/css/NoticeList.module.css
  src/admin/pages/notice/pages/NoticeInfo.js
  src/admin/pages/notice/pages/NoticeList.js
  src/admin/pages/reservation/css/ReservationInfo.module.css
  src/admin/pages/reservation/pages/ReservationEndInfo.js
  src/admin/pages/reservation/pages/ReservationTodayInfo.js
  src/admin/pages/review/css/ReviewInfo.module.css
  src/admin/pages/store/pages/StoreEdit.js
  src/admin/pages/store/pages/StoreInfo.js
  src/admin/pages/store/pages/StoreInfoRegist.js
  src/admin/pages/store/pages/StoreUserRegist.js
  src/admin/pages/user/css/UserInfo.module.css
  src/admin/pages/user/pages/UserInfo.js
  src/common/floatingBar/components/FloatingBar.js
  src/common/inquiry/api/GetUserNoAPI.js
  src/common/inquiry/api/inquiryInfoAPI.js
  src/common/inquiry/api/inquiryListAPI.js
  src/common/inquiry/api/reportInfoAPI.js
  src/common/inquiry/api/reportListAPI.js
  src/common/inquiry/components/DoInquiry.js
  src/common/inquiry/components/StoreInquiryEnter.js
  src/common/inquiry/components/StoreInquiryInfo.js
  src/common/inquiry/components/StoreInquiryList.js
  src/common/inquiry/components/StoreReportInfo.js
  src/common/inquiry/components/StoreUpdateInquiry.js
  src/common/inquiry/components/StoreUpdateReport.js
  src/common/inquiry/components/UserDoInquiry.js
  src/config/api.config.js
Labels: fix

#453 [FEATURE][ConnectGoolgleDrive]구글 드라이브 연결
  src/config/api.config.js
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/pages/InquiryDetails.js
Labels: feature

#455 [FEATURE][StoreDetail] 가게 상세페에지 이미지 드라이브 연결
  src/user/pages/storedetail/components/CreateReview.js
Labels: feature

#476 [FEATURE][FIX] 이번주 예약 그래프
  src/store/pages/bossStore/api/Graph.js
  src/store/pages/bossStore/components/WeeklyReservationGraph.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
Labels: fix

#479 메인 푸시
  Dockerfile
  nginx.conf
  package.json
  src/config/api.config.js
Labels: merge

#480 메인 푸시2
  nginx.conf
  src/config/api.config.js
Labels: merge

#481 메인 푸시 3
  nginx.conf
  package.json
Labels: merge

#482 메인 푸시 4
  .github/workflows/deploy.yml
Labels: merge

#484 메인 머지6
  Dockerfile
  nginx.conf
  src/config/api.config.js
Labels: merge

#487 [FIX][ForComplement]문제있는 부분 여러가지 수정
  package-lock.json
  src/App.js
  src/admin/components/AdminHeader.js
  src/common/authContext/UserRole.js
  src/common/header/components/BossHeader.js
  src/common/header/components/Header.js
  src/user/pages/login/pages/Login.js
  src/user/pages/main/Main.js
  src/user/pages/mypage/component/MyProfile.js
  src/user/pages/mypage/pages/Reservation.js
  src/user/pages/mypage/pages/ReservationDetail.js
  src/user/pages/storedetail/components/Calendar.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/components/test.js
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: bug, fix

#489 [FIX][StoreDetail] 리뷰 작성 권한 오류 해결
  src/common/header/css/header.css
  src/user/pages/storedetail/components/CreateReview.js
Labels: bug, fix

#493 [FIX][MAIN] 메인 가게 연결 수정
  package-lock.json
  src/store/layouts/BossLayout.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
Labels: fix

#500 [FIX][FixForComplement]약관 삽입 및 수정사항
  src/common/header/components/BossHeader.js
  src/store/layouts/BossLayout.js
  src/store/pages/bossInquiry/components/SpecificReviewModal.js
  src/store/pages/bossInquiry/pages/SpecificInquiry.js
  src/store/pages/bossInquiry/pages/TotalInquiryPage.js
  src/store/pages/bossNotice/components/BossSpecificNotice.js
  src/store/pages/bossNotice/components/BossTotalNotice.js
  src/store/pages/bossReview/components/SpecificReview.js
  src/store/pages/bossReview/pages/TotalReview.js
  src/store/pages/storeInfo/components/BossBanner.js
  src/store/pages/storeInfo/components/BossMenu.js
  src/store/pages/storeInfo/components/BossProfile.js
  src/store/pages/storeInfo/page/BossStoreInfoPage.js
  src/user/pages/signup/pages/Signup.js
Labels: bug, feature, fix

#502 [FIX][INQUIRY] 문의하기 수정
  src/common/inquiry/components/DoInquiry.js
Labels: fix

#504 [FIX][Total] CSS 반응형 수정
  src/common/error/css/error403.module.css
  src/common/error/css/error404.module.css
  src/common/error/css/error500.module.css
  src/common/floatingBar/css/floatingbar.module.css
  src/common/footer/css/footer.module.css
  src/common/footer/css/reset.module.css
  src/common/header/css/bossHeader.module.css
  src/common/header/css/reset.css
  src/common/inquiry/css/reset.css
  src/common/reset/reset.css
  src/store/layouts/BossLayout.js
  src/store/pages/bossInquiry/css/specificInquiry.module.css
  src/store/pages/bossInquiry/css/specificInquiry.module.scss
  src/store/pages/bossInquiry/css/specificReviewModal.module.css
  src/store/pages/bossReview/css/specificReview.module.css
  src/store/pages/bossReview/css/totalReview.module.css
  src/store/pages/storeInfo/css/bossBanner.module.css
  src/store/pages/storeInfo/css/bossMenu.module.css
  src/store/pages/storeInfo/css/bossProfile.module.css
  src/store/pages/storeInfo/css/bossStoreInfoPage.module.css
  src/user/pages/announcement/css/specificNotice.module.css
  src/user/pages/announcement/css/totalNotice.module.css
  src/user/pages/find/css/reset.css
  src/user/pages/info/css/footer.module.css
  src/user/pages/login/css/reset.css
  src/user/pages/main/component/Map.css
  src/user/pages/main/css/footer.module.css
  src/user/pages/main/css/main.css
  src/user/pages/mypage/css/reset.css
  src/user/pages/reservation/css/kakaoMap.module.css
  src/user/pages/reservation/css/profile.module.css
  src/user/pages/reservation/css/representativePhoto.module.css
  src/user/pages/reservation/css/reservation.module.css
  src/user/pages/reservation/css/reservationInfo.module.css
  src/user/pages/reservation/css/termsOfUse.module.css
  src/user/pages/search/css/footer.module.css
  src/user/pages/search/css/search.module.css
  src/user/pages/signup/css/reset.css
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/css/banner.module.css
  src/user/pages/storedetail/css/footer.module.css
  src/user/pages/storedetail/css/kakaoMap.module.css
  src/user/pages/storedetail/css/menu.module.css
  src/user/pages/storedetail/css/profile.module.css
  src/user/pages/storedetail/css/reservation.module.css
  src/user/pages/storedetail/css/review.module.css
  src/user/pages/storedetail/css/storedetail.module.css
  src/user/pages/storedetail/css/userStorePage.module.css
  src/user/pages/storedetail/pages/Review.js
Labels: fix

#511 [FIX][BOSSPAGE] 사장님 페이지 콘솔 오류 해결
  src/store/layouts/BossLayout.js
  src/store/pages/bossStore/pages/BossPage.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
Labels: fix

#515 [FIX][StoreDetail] 가게 상세페이지 이미지 없을 때 기본 이미지 반환
  src/user/layouts/css/userlayout.module.css
  src/user/pages/reservation/components/RepresentativePhoto.js
  src/user/pages/reservation/images/basicRepPhoto.png
  src/user/pages/storedetail/components/Banner.js
  src/user/pages/storedetail/components/CreateReview.js
  src/user/pages/storedetail/components/Menu.js
  src/user/pages/storedetail/components/Profile.js
  src/user/pages/storedetail/pages/Review.js
  src/user/pages/storedetail/pages/StoreDetail.js
Labels: fix

#513 [FIX][ALL] 공지사항, 사장님페이지, qr체크 수정
  src/config/api.config.js
  src/store/pages/bossReview/pages/TotalReview.js
  src/store/pages/qrCheck/api/QrInfoAPI.js
  src/store/pages/qrCheck/components/ExistenxeQr.js
  src/store/pages/qrCheck/components/NotFoundQr.js
  src/user/pages/announcement/components/SpecificNotice.js
  src/user/pages/announcement/components/TotalNotice.js
  src/user/pages/main/Main.js
  src/user/pages/main/component/Map.js
Labels: fix
